/* tables */
INSERT INTO regiones (id, nombre) VALUES (1, 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES (2, 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES (3, 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES (6, 'Africa');
INSERT INTO regiones (id, nombre) VALUES (7, 'Oceanía');
INSERT INTO regiones (id, nombre) VALUES (8, 'Antártida');
INSERT INTO regiones (id, nombre) VALUES (9, 'Polo Norte');

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Pedro', 'Hernandez', 'hernandez@hotmail.com', '1996-03-11');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (2, 'Adrian', 'Perez', 'perez@hotmail.com', '1996-03-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Elmer', 'Casas', 'casas@hotmail.com', '1991-07-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Juan', 'Rojas', 'rojas@hotmail.com', '2000-05-10');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Maria', 'Bonifacio', 'bonifacio@hotmail.com', '1999-07-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Joiselyn', 'Cauti', 'cauti@hotmail.com', '1991-05-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (9, 'Katy', 'Castillo', 'castillo@hotmail.com', '1986-05-17');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8, 'Shen', 'Roman', 'roman@hotmail.com', '1980-01-13');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Cap', 'Rodriguez', 'rodriguez@hotmail.com', '1990-05-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (6, 'Karol', 'Alejos', 'alejos@hotmail.com', '1997-12-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Mariana', 'Caceres', 'caceres@hotmail.com', '2001-01-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Yerard', 'Benites', 'benites@hotmail.com', '1993-07-10');

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Pedro', 'Hernandez', 'hernandez@hotmail.com', '1996-03-11');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (2, 'Adrian', 'Perez', 'perez@hotmail.com', '1996-03-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Elmer', 'Casas', 'casas@hotmail.com', '1991-07-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Juan', 'Rojas', 'rojas@hotmail.com', '2000-05-10');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Maria', 'Bonifacio', 'bonifacio@hotmail.com', '1999-07-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Joiselyn', 'Cauti', 'cauti@hotmail.com', '1991-05-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (9, 'Katy', 'Castillo', 'castillo@hotmail.com', '1986-05-17');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8, 'Shen', 'Roman', 'roman@hotmail.com', '1980-01-13');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Cap', 'Rodriguez', 'rodriguez@hotmail.com', '1990-05-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (6, 'Karol', 'Alejos', 'alejos@hotmail.com', '1997-12-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Mariana', 'Caceres', 'caceres@hotmail.com', '2001-01-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Yerard', 'Benites', 'benites@hotmail.com', '1993-07-10');

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Pedro', 'Hernandez', 'hernandez@hotmail.com', '1996-03-11');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (2, 'Adrian', 'Perez', 'perez@hotmail.com', '1996-03-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Elmer', 'Casas', 'casas@hotmail.com', '1991-07-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Juan', 'Rojas', 'rojas@hotmail.com', '2000-05-10');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Maria', 'Bonifacio', 'bonifacio@hotmail.com', '1999-07-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Joiselyn', 'Cauti', 'cauti@hotmail.com', '1991-05-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (9, 'Katy', 'Castillo', 'castillo@hotmail.com', '1986-05-17');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8, 'Shen', 'Roman', 'roman@hotmail.com', '1980-01-13');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Cap', 'Rodriguez', 'rodriguez@hotmail.com', '1990-05-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (6, 'Karol', 'Alejos', 'alejos@hotmail.com', '1997-12-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Mariana', 'Caceres', 'caceres@hotmail.com', '2001-01-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Yerard', 'Benites', 'benites@hotmail.com', '1993-07-10');

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Pedro', 'Hernandez', 'hernandez@hotmail.com', '1996-03-11');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (2, 'Adrian', 'Perez', 'perez@hotmail.com', '1996-03-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Elmer', 'Casas', 'casas@hotmail.com', '1991-07-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Juan', 'Rojas', 'rojas@hotmail.com', '2000-05-10');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Maria', 'Bonifacio', 'bonifacio@hotmail.com', '1999-07-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Joiselyn', 'Cauti', 'cauti@hotmail.com', '1991-05-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (9, 'Katy', 'Castillo', 'castillo@hotmail.com', '1986-05-17');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8, 'Shen', 'Roman', 'roman@hotmail.com', '1980-01-13');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Cap', 'Rodriguez', 'rodriguez@hotmail.com', '1990-05-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (6, 'Karol', 'Alejos', 'alejos@hotmail.com', '1997-12-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Mariana', 'Caceres', 'caceres@hotmail.com', '2001-01-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Yerard', 'Benites', 'benites@hotmail.com', '1993-07-10');

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Pedro', 'Hernandez', 'hernandez@hotmail.com', '1996-03-11');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (2, 'Adrian', 'Perez', 'perez@hotmail.com', '1996-03-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Elmer', 'Casas', 'casas@hotmail.com', '1991-07-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Juan', 'Rojas', 'rojas@hotmail.com', '2000-05-10');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, 'Maria', 'Bonifacio', 'bonifacio@hotmail.com', '1999-07-20');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, 'Joiselyn', 'Cauti', 'cauti@hotmail.com', '1991-05-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (9, 'Katy', 'Castillo', 'castillo@hotmail.com', '1986-05-17');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8, 'Shen', 'Roman', 'roman@hotmail.com', '1980-01-13');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Cap', 'Rodriguez', 'rodriguez@hotmail.com', '1990-05-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (6, 'Karol', 'Alejos', 'alejos@hotmail.com', '1997-12-30');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Mariana', 'Caceres', 'caceres@hotmail.com', '2001-01-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, 'Yerard', 'Benites', 'benites@hotmail.com', '1993-07-10');